In [18]:
!ls

database
DB test.ipynb
images
main.py
Procfile
README.md
requirements.txt
static
templates
Untitled.ipynb

In [19]:
import sqlite3

mycursor = sqlite3.connect('database/user.db')

In [20]:
query1 = """CREATE TABLE ABOUT_ME (TID VARCHAR(255) NOT NULL,
            NAME VARCHAR(255), 
            HEADING VARCHAR(255), 
            DESCRIPTION VARCHAR(1000), 
            EMAIL VARCHAR(255),
            LINKEDIN VARCHAR(255),
            GIT VARCHAR(255),
            KAGGLE VARCHAR(255),
            PRIMARY KEY (TID))"""

query2 = """CREATE TABLE EDUCATION (TID VARCHAR(255) NOT NULL,
            DEGREE VARCHAR(255),
            UNIVERSITY VARCHAR(255),
            LOCATION VARCHAR(255),
            SCORE FLOAT,
            START_DATE DATE,
            END_DATE DATE,
            DURATION FLOAT,
            PRIMARY KEY (TID))"""

query3 = """CREATE TABLE EXPERIENCE (TID VARCHAR(255) NOT NULL,
            DESIGNATION VARCHAR(255),
            COMPANY VARCHAR(255),
            LOCATION VARCHAR(255),
            START_DATE DATE,
            END_DATE DATE,
            DURATION FLOAT,
            DETAILS VARCHAR(255),
            PRIMARY KEY (TID))"""

query4 = """CREATE TABLE SKILLS (TID VARCHAR(255) NOT NULL,
            SKILL_NAME VARCHAR(255), PRIMARY KEY(TID))"""

query5 = """CREATE TABLE INTEREST (TID VARCHAR(255) NOT NULL,
            INTEREST_NAME VARCHAR(255), PRIMARY KEY(TID))"""

query6 = """CREATE TABLE PROFESSION (TID VARCHAR(255) NOT NULL,
            DESCRIPTION VARCHAR(255), PRIMARY KEY(TID))"""

query7 = """CREATE TABLE CERTIFICATES (TID VARCHAR(255) NOT NULL,
            CERTIFICATE_NAME VARCHAR(255),
            ISSUER VARCHAR(255),
            LOCATION VARCHAR(255),
            CERTIFICATE_LINK VARCHAR(255),
            START_DATE DATE,
            END_DATE DATE,
            DURATION FLOAT,
            DETAILS VARCHAR(255),
            PRIMARY KEY(TID))"""

query8 = """CREATE TABLE PROJECTS (TID VARCHAR(255) NOT NULL,
            PROJECT_NAME VARCHAR(255),
            GIT_LINK VARCHAR(255),
            DEPLOYMENT_LINK VARCHAR(255),
            START_DATE DATE,
            END_DATE DATE,
            DURATION FLOAT,
            DETAILS VARCHAR(255),
            PRIMARY KEY (TID))"""

In [6]:
# mycursor.execute(query1)
# mycursor.execute(query2)
# mycursor.execute(query3)
# mycursor.execute(query4)
# mycursor.execute(query5)
# mycursor.execute(query6)
mycursor.execute(query7)
# mycursor.execute(query8)
mycursor.commit()

In [21]:
def strip_string(s):
    s = s.strip()
    s = s.replace('\n', '')
    for i in range(5):
        s = s.replace('  ', ' ')
    return s

In [22]:
from bs4 import BeautifulSoup as bs
from urllib.request import urlopen as uReq

In [23]:
html_file = open('templates/index.html', 'r')
index_data = html_file.read()
formatted_data = bs(index_data, 'html')
formatted_data

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&amp;display=swap" rel="stylesheet"/>
<link href="../static/style.css" rel="stylesheet"/>
<title>Biswajit Basak's Resume</title>
</head>
<body>
<div class="resume">
<div class="column">
<section class="profile">
<h1>{{main_dict['table1_dict']['name']}}</h1>
<p><em>{{main_dict['table1_dict']['heading']}}</em></p>
<img alt="" src="/static/images/photo.jpg"/>
</section>
<section class="section1">
<h2>About Me</h2>
<section class="objectives">
<p>{{main_dict['table1_dict']['description']}}</p>
</section>
<br/><br/><br/>
<section class="education">
<h2>Education</h2>
<ul class="timeline">
<li class="event">
<span class="duration">From {{main_dict['table2_dict']['start_date']}} To {{main_dict['table2_dict']['end_date']}} ({{main_dict['table2_dict']['duration']}} Years) </span>
<div class="content">
<h3>{{main_dict['table2_dict']['degree']}}</h3>
<p><em>{{main_dict['table2_dict']['university']}}</em></p>
<p>CGPA / Percentage: {{main_dict['table2_dict']['score']}}</p>
</div>
</li>
</ul>
</section>
<section class="experience">
<h2>Experience</h2>
<ul class="timeline">
<li class="event">
<span class="duration">From {{main_dict['table3_dict']['start_date']}} To {{main_dict['table3_dict']['end_date']}} ({{main_dict['table3_dict']['duration']}} Years)</span>
<div class="content">
<h3>{{main_dict['table3_dict']['designation']}}</h3>
<p>{{main_dict['table3_dict']['company']}}, {{main_dict['table3_dict']['location']}}</p>
<p>
                  {{main_dict['table3_dict']['details']}}
                </p>
</div>
</li>
</ul>
</section>
<br/>
<h2>Skills/Interests</h2>
<ul>
<li>
<h3>Skills</h3>
<ol type="1">
              {% for i in main_dict['table4_dict'] %}
                <li>{{i}}</li>
              {% endfor %}
            </ol>
</li>
<li>
<h3>Interests</h3>
<ol type="1">
              {% for i in main_dict['table5_dict'] %}
                <li>{{i}}</li>
              {% endfor %}
            </ol>
</li>
</ul>
</section>
</div>
<div class="column">
<section class="contact">
<h2>Profile</h2>
<br/>
<ul>
<li><a href="mailto:{{main_dict['table1_dict']['email']}}">{{main_dict['table1_dict']['email']}}</a>
<img alt="" src="/static/images/mail-64.png"/>
</li>
<li><a href="https://www.{{main_dict['table1_dict']['linkedin']}}" target="_blank">{{main_dict['table1_dict']['linkedin']}}</a>
<img alt="" src="/static/images/linkedin-5-64.png"/>
</li>
<li><a href="https://{{main_dict['table1_dict']['git']}}" target="_blank">{{main_dict['table1_dict']['git']}}</a>
<img alt="" src="/static/images/github-10-64.png"/>
</li>
<li><a href="https://www.{{main_dict['table1_dict']['kaggle']}}" target="_blank">{{main_dict['table1_dict']['kaggle']}}</a>
<img alt="" src="/static/images/kaggle.png"/>
</li>
</ul>
</section>
<section class="section1">
<h2>Why me ?</h2>
<section class="objectives">
<p>
<ol type="1">
            {% for i in main_dict['table6_dict'] %}
                <li>{{i}}</li>
              {% endfor %}
          </ol>
</p>
</section>
<section class="certificates">
<h2>Certificates</h2>
<ul class="timeline">
<li class="event">
<span class="duration">12/2019</span>
<span class="duration">01/2020</span>
<span class="duration">2</span>
<div class="content">
<h3>AI ML Certification</h3>
<h3>Wipro</h3>
<p>Online</p>
<p>Completed AI ML Certification from Wipro, which included Python
                  Programming assignments and Machine Learning Assignments</p>
<p>
<a href="https://github.com/JuelBasak/Certificates/blob/master/Wipro/AI%20App%20Developer%20program_20122958.pdf" style="color:blue;" target="_blank">Certificate Link</a>
</p>
</div>
</li>
</ul>
<br/>
<ul class="timeline">
<li class="event">
<span class="duration">03/2020</span>
<span class="duration">04/2020</span>
<span class="duration">2</span>
<div class="content">
<h3>Machine Learning Certificate</h3>
<h3>365DataScience</h3>
<p>Online</p>
<p>Completed Multiple certifications on Python, Statistics, Mathematics, Deep Learning etc. </p>
<p>
<a href="https://github.com/JuelBasak/Certificates/tree/master/365%20Data%20Science" style="color:blue;" target="_blank">Certificate Link</a>
</p>
</div>
</li>
</ul>
<br/>
<ul class="timeline">
<li class="event">
<span class="duration">09/2017</span>
<span class="duration">09/2017</span>
<span class="duration">2</span>
<div class="content">
<h3>IoT using Arduino</h3>
<h3>Skify Labs</h3>
<p>Bangalore</p>
<p>Build an IOT Device using breadboard and arduino to measure the nearby temperature
                  and upload the data using the wifi module to a server.</p>
<p>
<a href="https://github.com/JuelBasak/Certificates/blob/master/SkiFy%20labs%20Certificate.pdf" style="color:blue;" target="_blank">Certificate Link</a>
</p>
</div>
</li>
</ul>
</section>
</section>
</div>
</div>
<section class="project">
<h2>Projects</h2>
<ul class="timeline">
<li class="event">
<span class="duration">01/2022</span>
<span class="duration">01/2022</span>
<div class="content">
<h3>Football Player Overall Score Prediction</h3>
<!-- <p><em>Bangalore</em></p> -->
<p>This is a project that is built using the Python and Flask Framework.
            This webapp can predict the overall score of a football player given various attributes and match
            information.
            This webapp is deployed on the Heroku Platform.
          </p>
<p>
<a href="https://ml-project-ineuron.herokuapp.com/" style="color:blue;" target="_blank">Project
              Deployment Link</a>
</p>
</div>
</li>
</ul>
<br/>
<ul class="timeline">
<li class="event">
<span class="duration">09/2021</span>
<span class="duration">09/2021</span>
<div class="content">
<h3>Income Prediction using XGBoost Algorithm</h3>
<!-- <p><em>Bangalore</em></p> -->
<p>Built using the Flask Framework, this webpage takes in user details such as age, workclass etc, and
            tries to predict whether the
            person earns more than 50K per month or less. This project is Deployed on Heroku Cloud Platform.
          </p>
<p>
<a href="https://income-prediction-xgboost.herokuapp.com/" style="color:blue;" target="_blank">Project
              Deployment Link</a>
</p>
</div>
</li>
</ul>
<br/>
<ul class="timeline">
<li class="event">
<span class="duration">09/2021</span>
<span class="duration">09/2021</span>
<div class="content">
<h3>Boston Housing Price Prediction using Random Forest</h3>
<!-- <p><em>Bangalore</em></p> -->
<p>The Project uses Bagging Ensemble Machine Learning Technique to predict the Boston House Prices. This
            is a
            Regression Problem.
            It takes some necessary data for the prediction and is able to predict prices based upon the provided
            data.
            This Project is created using the Flask Framework and is deployed on Heroku Cloud Platform.
          </p>
<p>
<a href="https://boston-housing-randomforest.herokuapp.com/" style="color:blue;" target="_blank">Project
              Deployment Link</a>
</p>
</div>
</li>
</ul>
<br/>
<ul class="timeline">
<li class="event">
<span class="duration">08/2021</span>
<span class="duration">08/2021</span>
<div class="content">
<h3>Titanic Survival Prediction using Decision Tree Algorithm</h3>
<!-- <p><em>Bangalore</em></p> -->
<p>This project is built by analyzing the titanic dataset. The machine learning model can predict
            if a passenger survived the Historic Titanic Incident provided some of the
            passenger details. Flask framework with the help of Decision Tree is used to Built the Model. and
            the model is deployed on Heroku Cloud Platform.
          </p>
<p>
<a href="https://titanic-classifi-decision-tree.herokuapp.com/" style="color:blue;" target="_blank">Project
              Deployment Link</a>
</p>
</div>
</li>
</ul>
<br/>
<ul class="timeline">
<li class="event">
<span class="duration">08/2021</span>
<span class="duration">08/2021</span>
<div class="content">
<h3>Red Wine Quality Prediction using Decision Tree Algorithm</h3>
<!-- <p><em>Bangalore</em></p> -->
<p>This Machine Learning Model is able to assign a quality score to the Red Wine based upon the
            properties/composition
            of the Wine. It is built using the Flask Framework and deployed on Heroku Cloud Platform.
          </p>
<p>
<a href="https://redwine-quality-prediction.herokuapp.com/" style="color:blue;" target="_blank">Project
              Deployment Link</a>
</p>
</div>
</li>
</ul>
<br/>
<ul class="timeline">
<li class="event">
<span class="duration">07/2021</span>
<span class="duration">07/2021</span>
<div class="content">
<h3>Woman Affair Classification using Logistic Regression</h3>
<!-- <p><em>Bangalore</em></p> -->
<p>A Webpage that takes in all the required details of a Woman and is able to predict whether the
            woman has any affair or not. This project is built using the Flask Framework, it uses the Logistic
            Regression Algorithm.
            And this is deployed on Heroku Cloud Platform.
          </p>
<p>
<a href="http://woman-affair-classifier.herokuapp.com/" style="color:blue;" target="_blank">Project
              Deployment Link</a>
</p>
</div>
</li>
</ul>
<br/>
<ul class="timeline">
<li class="event">
<span class="duration">07/2021</span>
<span class="duration">07/2021</span>
<div class="content">
<h3>Boston Housing Price Prediction using Linear Regression</h3>
<!-- <p><em>Bangalore</em></p> -->
<p>The Project uses the classical Linear Regression Model to predict the Boston House Prices.
            The Housing Details are provided to the algorithm and the algorithm is able to predict the Housing
            Prices.
            This Project is created using the Flask Framework and is deployed on Heroku Cloud Platform.
          </p>
<p>
<a href="https://boston-housing-price-linear.herokuapp.com/" style="color:blue;" target="_blank">Project
              Deployment Link</a>
</p>
</div>
</li>
</ul>
<br/>
<ul class="timeline">
<li class="event">
<span class="duration">06/2021</span>
<span class="duration">06/2021</span>
<div class="content">
<h3>Webscapper built using Python's Flask Framework using
            Selenium</h3>
<!-- <p><em>Bangalore</em></p> -->
<p>This web scapper scraps data from MonsterIndia website. It scraps
            all the Job related details. Built using Selenium and integrated with
            MongoDB.</p>
<p>
<!-- <a style="color:blue;" href="" target="_blank">Project Deployment Link</a> -->
</p>
</div>
</li>
</ul>
<br/>
<ul class="timeline">
<li class="event">
<span class="duration">06/2021</span>
<span class="duration">06/2021</span>
<div class="content">
<h3>Webscrapper built using Python's Flask Framework</h3>
<!-- <p><em>Bangalore</em></p> -->
<p>This is a Web Scrapper built using Python and Flask Framework. It
            scraps Flipkart's website and shows all the user names, reviews,
            ratings, and descriptions given by that user. This program is
            deployed in Heroku Platform.</p>
<p>
<a href="https://flask-fl-scrapper.herokuapp.com/" style="color:blue;" target="_blank">Project
              Deployment Link</a>
</p>
</div>
</li>
</ul>
<br/>
<ul class="timeline">
<li class="event">
<span class="duration">02/2019</span>
<span class="duration">05/2019</span>
<div class="content">
<h3>Analysis of Trivial and Bio-inspired Algorithms</h3>
<p><em>Bangalore</em></p>
<p>To design and analyse the performance of various bio-inspired
            algorithms and compare them with trivial algorithms to solve real
            world issues of wireless sensor networks.</p>
<p>
<a href="https://github.com/JuelBasak/Final-Project-B.Tech" style="color:blue;" target="_blank">Documentation Link</a>
</p>
</div>
</li>
</ul>
<br/>
<ul class="timeline">
<li class="event">
<span class="duration">02/2018</span>
<span class="duration">05/2018</span>
<div class="content">
<h3>Design and development of an application for Election
            Analysis and Voting</h3>
<p><em>Bangalore</em></p>
<p>An app that is designed and built in android studio, which provides
            all the details of the political parties, leaders and current political
            news. Through this app, the registered user can also cast their vote.
            The development of the app required knowledge of web
            development skills such as HTML, CSS, XML and PHP. Also the skills
            for android studio was required.</p>
<p>
<a href="https://github.com/JuelBasak/Mini-Project-BTech" style="color:blue;" target="_blank">Documentation
              Link</a>
</p>
</div>
</li>
</ul>
<br/>
<ul class="timeline">
<li class="event">
<span class="duration">09/2017</span>
<span class="duration">09/2017</span>
<div class="content">
<h3>Monitor Temperature using IOT Devices</h3>
<p><em>Bangalore</em></p>
<p>IoT using Adreno to measure live temperature of the ambient
            atmosphere using temperature sensors and to transfer the sensed
            data and plot it in the hosting website as a graph for data analysis.
            The knowledge of adreno board, temperature sensors and bread
            board are required as a pre-requisite.</p>
</div>
</li>
</ul>
</section></body>
</html>

# Table 1 Contents

In [29]:
tid = 'TB101'
name = formatted_data.findAll("section", {"class": "profile"})[0].h1.text
heading = formatted_data.findAll("section", {"class": "profile"})[0].p.em.text
description = strip_string(formatted_data.findAll("section", {"class": "objectives"})[0].p.text)
email = formatted_data.findAll("section", {"class": "contact"})[0].findAll('a')[0].text
linkedin = formatted_data.findAll("section", {"class": "contact"})[0].findAll('a')[1].text
git = formatted_data.findAll("section", {"class": "contact"})[0].findAll('a')[2].text
kaggle = formatted_data.findAll("section", {"class": "contact"})[0].findAll('a')[3].text

In [11]:
print(tid)
print(name)
print(heading)
print(description)
print(email)
print(linkedin)
print(git)
print(kaggle)

TB101
Biswajit Basak
Computer Science Graduate | AI ML Enthusiast | Pythoneer
I am an Engineering Graduate. I pursued my Bachelors Degree in Computer Science. I am passionate about coding and machine learning. I am always enthusiastic about new technologies and eager to learn new skills and broaden my knowledge. In my spare time, I make videos on YouTube. Traveling and exploring places is also a part of my life.
juelbasak@gmail.com
linkedin.com/in/biswajit-basak-30bba185
github.com/JuelBasak
kaggle.com/juelbasak

In [20]:
n = 15

In [34]:
query = f"""INSERT INTO ABOUT_ME (TID, NAME, HEADING, DESCRIPTION, EMAIL, LINKEDIN, GIT, KAGGLE) VALUES ("{tid}","{name}", "{heading}", "{description}", "{email}", "{linkedin}", "{git}", "{kaggle}")"""

query

'INSERT INTO ABOUT_ME (TID, NAME, HEADING, DESCRIPTION, EMAIL, LINKEDIN, GIT, KAGGLE) VALUES ("TB101","Biswajit Basak", "Computer Science Graduate | AI ML Enthusiast | Pythoneer", "I am an Engineering Graduate. I pursued my Bachelors Degree in Computer Science. I am passionate about coding and machine learning. I am always enthusiastic about new technologies and eager to learn new skills and broaden my knowledge. In my spare time, I make videos on YouTube. Traveling and exploring places is also a part of my life.", "juelbasak@gmail.com", "linkedin.com/in/biswajit-basak-30bba185", "github.com/JuelBasak", "kaggle.com/juelbasak")'

In [35]:
mycursor.execute(query)
mycursor.commit()

# Table 2 Contents

In [38]:
tid = 'TB201'
degree = formatted_data.findAll("section", {"class": "education"})[0].h3.text
university = 'M. S. Ramaiah University of Applied Sciences'
location = 'Bangalore'
score = 7.73
start_date = '09/2015'
end_date = '05/2019'
duration = '4'

In [41]:
query = f"""INSERT INTO EDUCATION (TID, DEGREE, UNIVERSITY, LOCATION, SCORE, START_DATE, END_DATE, DURATION) VALUES ("{tid}","{degree}", "{university}", "{location}", "{score}", "{start_date}", "{end_date}", "{duration}")"""
mycursor.execute(query)
mycursor.commit()

# Table 3 Contents

In [42]:
tid = 'TB301'
designation = formatted_data.findAll("section", {"class": "experience"})[0].h3.text
company = 'Wipro'
location = 'Chennai'
start_date = '10/2019'
end_date = '03/2021'
duration = '1.5'
details = strip_string(formatted_data.findAll("section", {"class": "experience"})[0].findAll('p')[1].text)

In [ ]:
"""CREATE TABLE EXPERIENCE (TID VARCHAR(255) NOT NULL,
            DESIGNATION VARCHAR(255),
            COMPANY VARCHAR(255),
            LOCATION VARCHAR(255),
            START_DATE DATE,
            END_DATE DATE,
            DURATION FLOAT,
            DETAILS VARCHAR(255),
            PRIMARY KEY (TID))"""

In [43]:
query = f"""INSERT INTO EXPERIENCE (TID, DESIGNATION, COMPANY, LOCATION, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("{tid}","{designation}", "{company}", "{location}", "{start_date}", "{end_date}", "{duration}", "{details}")"""
mycursor.execute(query)
mycursor.commit()

# Table 4 contents

In [54]:
data = formatted_data.findAll("section", {"class": "section1"})[0].findAll('ol')[0].findAll('li')

table_type = 0

temp = []
table4 = {}

for i in range(len(data)):
    temp.append(data[i].text)
    
temp

['Python Programming',
 'Machine Learning',
 'Flask Framework',
 'MongoDB',
 'SQL',
 'HTML',
 'CSS',
 'Bootstrap',
 'Git/Github',
 'Linux Familiarity']

In [63]:
n = 1
for i in temp:
    tid = 'TB40' + str(n)
    query = f"""INSERT INTO SKILLS (TID, SKILL_NAME) VALUES ("{tid}", "{i}")"""
    mycursor.execute(query)
    
    n += 1

mycursor.commit()

IntegrityError: UNIQUE constraint failed: SKILLS.TID

# Table 5 Contents

In [69]:
data = formatted_data.findAll("section", {"class": "section1"})[0].findAll('ol')[1].findAll('li')

table_type = 1

temp = []

for i in range(len(data)):
    temp.append(data[i].text)
    
temp

['Programming', 'Gaming', 'Making Videos', 'Exploring New Places']

In [70]:
n = 1
for i in temp:
    tid = 'TB50' + str(n)
    query = f"""INSERT INTO INTEREST (TID, INTEREST_NAME) VALUES ("{tid}", "{i}")"""
    mycursor.execute(query)
    
    n+=1

mycursor.commit()

# Table 6 contents

In [72]:
data = formatted_data.findAll("section", {"class": "section1"})[1].ol.findAll('li')
n = 1

for i in range(len(data)):
    tid = 'TB60' + str(n)
    query = f"""INSERT INTO PROFESSION (TID, DESCRIPTION) VALUES ("{tid}", "{strip_string(data[i].text)}")"""
    mycursor.execute(query)
    
    n+=1
    
mycursor.commit()

In [ ]:
query = f"""INSERT INTO EXPERIENCE (TID, DESIGNATION, COMPANY, LOCATION, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("{tid}","{designation}", "{company}", "{location}", "{start_date}", "{end_date}", "{duration}", "{details}")"""
mycursor.execute(query)
mycursor.commit()

# Table 7 Content

In [24]:
data = formatted_data.findAll("section", {"class": "certificates"})[0].findAll("ul", {"class": "timeline"})
n = 1

for i in range(len(data)):
    tid = 'TB70' + str(n)
    
    certificate_name = data[i].h3.text
    issuer = data[i].findAll('h3')[1].text
    location = data[i].p.text
    certificate_link = data[i].a.get('href')
    start_date = data[i].findAll('span')[0].text
    end_date = data[i].findAll('span')[1].text
    duration = data[i].findAll('span')[2].text
    details = data[i].findAll('p')[1].text
    
    
    print('TID -> ', tid)
    print('certificate_name -> ', strip_string(certificate_name))
    print('Issuer -> ', issuer)
    print('Location -> ', strip_string(location))
    print('certificate_link -> ', strip_string(certificate_link))
    print('Start Date -> ', strip_string(start_date))
    print('End Date -> ', strip_string(end_date))
    print('Duration -> ', strip_string(duration))
    print('Details -> ', strip_string(details))
    
    print('-' * 100)
    n += 1
    
    
    query = f"""INSERT INTO CERTIFICATES (TID, CERTIFICATE_NAME, ISSUER, LOCATION, CERTIFICATE_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("{tid}","{strip_string(certificate_name)}", "{issuer}", "{strip_string(location)}", "{strip_string(certificate_link)}", "{strip_string(start_date)}", "{strip_string(end_date)}", "{strip_string(duration)}", "{strip_string(details)}")"""
    print(query)
    mycursor.execute(query)
    mycursor.commit()

TID ->  TB701
certificate_name ->  AI ML Certification
Issuer ->  Wipro
Location ->  Online
certificate_link ->  https://github.com/JuelBasak/Certificates/blob/master/Wipro/AI%20App%20Developer%20program_20122958.pdf
Start Date ->  12/2019
End Date ->  01/2020
Duration ->  2
Details ->  Completed AI ML Certification from Wipro, which included Python Programming assignments and Machine Learning Assignments
----------------------------------------------------------------------------------------------------
INSERT INTO CERTIFICATES (TID, CERTIFICATE_NAME, ISSUER, LOCATION, CERTIFICATE_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB701","AI ML Certification", "Wipro", "Online", "https://github.com/JuelBasak/Certificates/blob/master/Wipro/AI%20App%20Developer%20program_20122958.pdf", "12/2019", "01/2020", "2", "Completed AI ML Certification from Wipro, which included Python Programming assignments and Machine Learning Assignments")
TID ->  TB702
certificate_name ->  Machine Learning Certificate
Issuer ->  365DataScience
Location ->  Online
certificate_link ->  https://github.com/JuelBasak/Certificates/tree/master/365%20Data%20Science
Start Date ->  03/2020
End Date ->  04/2020
Duration ->  2
Details ->  Completed Multiple certifications on Python, Statistics, Mathematics, Deep Learning etc.
----------------------------------------------------------------------------------------------------
INSERT INTO CERTIFICATES (TID, CERTIFICATE_NAME, ISSUER, LOCATION, CERTIFICATE_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB702","Machine Learning Certificate", "365DataScience", "Online", "https://github.com/JuelBasak/Certificates/tree/master/365%20Data%20Science", "03/2020", "04/2020", "2", "Completed Multiple certifications on Python, Statistics, Mathematics, Deep Learning etc.")
TID ->  TB703
certificate_name ->  IoT using Arduino
Issuer ->  Skify Labs
Location ->  Bangalore
certificate_link ->  https://github.com/JuelBasak/Certificates/blob/master/SkiFy%20labs%20Certificate.pdf
Start Date ->  09/2017
End Date ->  09/2017
Duration ->  2
Details ->  Build an IOT Device using breadboard and arduino to measure the nearby temperature and upload the data using the wifi module to a server.
----------------------------------------------------------------------------------------------------
INSERT INTO CERTIFICATES (TID, CERTIFICATE_NAME, ISSUER, LOCATION, CERTIFICATE_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB703","IoT using Arduino", "Skify Labs", "Bangalore", "https://github.com/JuelBasak/Certificates/blob/master/SkiFy%20labs%20Certificate.pdf", "09/2017", "09/2017", "2", "Build an IOT Device using breadboard and arduino to measure the nearby temperature and upload the data using the wifi module to a server.")

In [3]:
mycursor.execute('DROP TABLE CERTIFICATES')
mycursor.commit()

# Table 8 Content

In [94]:
data = formatted_data.findAll("section", {"class": "project"})[0].findAll("ul", {"class": "timeline"})
n = 1

for i in range(len(data)):
    tid = 'TB80' + str(n)
    project_name = ''
    project_deployment_link = ''
    date = ''
    details = ''
    
    try:
    
        project_name = formatted_data.findAll("section", {"class": "project"})[0].findAll("ul", {"class": "timeline"})[i].h3.text

        project_deployment_link  = formatted_data.findAll("section", {"class": "project"})[0].findAll("ul", {"class": "timeline"})[i].a.get('href')

        start_date = formatted_data.findAll("section", {"class": "project"})[0].findAll("ul", {"class": "timeline"})[i].findAll('span')[0].text
        
        end_date = formatted_data.findAll("section", {"class": "project"})[0].findAll("ul", {"class": "timeline"})[i].findAll('span')[1].text
        
        details = formatted_data.findAll("section", {"class": "project"})[0].findAll("ul", {"class": "timeline"})[i].p.text
    
    except AttributeError:
        start_date = formatted_data.findAll("section", {"class": "project"})[0].findAll("ul", {"class": "timeline"})[i].findAll('span')[0].text
        
        end_date = formatted_data.findAll("section", {"class": "project"})[0].findAll("ul", {"class": "timeline"})[i].findAll('span')[1].text
        
        details = formatted_data.findAll("section", {"class": "project"})[0].findAll("ul", {"class": "timeline"})[i].p.text
    
        continue
        
    finally:
        print('tid -> ', tid)
        print('project_name -> ', strip_string(project_name))
        print('project_deployment_link -> ', strip_string(project_deployment_link))
        print('start date -> ', strip_string(start_date))
        print('end date -> ', strip_string(end_date))
        print('details -> ', strip_string(details))
        print('-' * 100)
        
        
        query = f"""INSERT INTO PROJECTS (TID, PROJECT_NAME, GIT_LINK, DEPLOYMENT_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("{tid}","{strip_string(project_name)}", "{''}", "{strip_string(project_deployment_link)}", "{strip_string(start_date)}", "{strip_string(end_date)}", "{strip_string(duration)}", "{strip_string(details)}")"""
        print(query)
        mycursor.execute(query)
        mycursor.commit()
        
        n += 1

tid ->  TB801
project_name ->  Football Player Overall Score Prediction
project_deployment_link ->  https://ml-project-ineuron.herokuapp.com/
start date ->  01/2022
end date ->  01/2022
details ->  This is a project that is built using the Python and Flask Framework. This webapp can predict the overall score of a football player given various attributes and match information. This webapp is deployed on the Heroku Platform.
----------------------------------------------------------------------------------------------------
INSERT INTO PROJECTS (TID, PROJECT_NAME, GIT_LINK, DEPLOYMENT_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB801","Football Player Overall Score Prediction", "", "https://ml-project-ineuron.herokuapp.com/", "01/2022", "01/2022", "2", "This is a project that is built using the Python and Flask Framework. This webapp can predict the overall score of a football player given various attributes and match information. This webapp is deployed on the Heroku Platform.")
tid ->  TB802
project_name ->  Income Prediction using XGBoost Algorithm
project_deployment_link ->  https://income-prediction-xgboost.herokuapp.com/
start date ->  09/2021
end date ->  09/2021
details ->  Built using the Flask Framework, this webpage takes in user details such as age, workclass etc, and tries to predict whether the person earns more than 50K per month or less. This project is Deployed on Heroku Cloud Platform.
----------------------------------------------------------------------------------------------------
INSERT INTO PROJECTS (TID, PROJECT_NAME, GIT_LINK, DEPLOYMENT_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB802","Income Prediction using XGBoost Algorithm", "", "https://income-prediction-xgboost.herokuapp.com/", "09/2021", "09/2021", "2", "Built using the Flask Framework, this webpage takes in user details such as age, workclass etc, and tries to predict whether the person earns more than 50K per month or less. This project is Deployed on Heroku Cloud Platform.")
tid ->  TB803
project_name ->  Boston Housing Price Prediction using Random Forest
project_deployment_link ->  https://boston-housing-randomforest.herokuapp.com/
start date ->  09/2021
end date ->  09/2021
details ->  The Project uses Bagging Ensemble Machine Learning Technique to predict the Boston House Prices. This is a Regression Problem. It takes some necessary data for the prediction and is able to predict prices based upon the provided data. This Project is created using the Flask Framework and is deployed on Heroku Cloud Platform.
----------------------------------------------------------------------------------------------------
INSERT INTO PROJECTS (TID, PROJECT_NAME, GIT_LINK, DEPLOYMENT_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB803","Boston Housing Price Prediction using Random Forest", "", "https://boston-housing-randomforest.herokuapp.com/", "09/2021", "09/2021", "2", "The Project uses Bagging Ensemble Machine Learning Technique to predict the Boston House Prices. This is a Regression Problem. It takes some necessary data for the prediction and is able to predict prices based upon the provided data. This Project is created using the Flask Framework and is deployed on Heroku Cloud Platform.")
tid ->  TB804
project_name ->  Titanic Survival Prediction using Decision Tree Algorithm
project_deployment_link ->  https://titanic-classifi-decision-tree.herokuapp.com/
start date ->  08/2021
end date ->  08/2021
details ->  This project is built by analyzing the titanic dataset. The machine learning model can predict if a passenger survived the Historic Titanic Incident provided some of the passenger details. Flask framework with the help of Decision Tree is used to Built the Model. and the model is deployed on Heroku Cloud Platform.
----------------------------------------------------------------------------------------------------
INSERT INTO PROJECTS (TID, PROJECT_NAME, GIT_LINK, DEPLOYMENT_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB804","Titanic Survival Prediction using Decision Tree Algorithm", "", "https://titanic-classifi-decision-tree.herokuapp.com/", "08/2021", "08/2021", "2", "This project is built by analyzing the titanic dataset. The machine learning model can predict if a passenger survived the Historic Titanic Incident provided some of the passenger details. Flask framework with the help of Decision Tree is used to Built the Model. and the model is deployed on Heroku Cloud Platform.")
tid ->  TB805
project_name ->  Red Wine Quality Prediction using Decision Tree Algorithm
project_deployment_link ->  https://redwine-quality-prediction.herokuapp.com/
start date ->  08/2021
end date ->  08/2021
details ->  This Machine Learning Model is able to assign a quality score to the Red Wine based upon the properties/composition of the Wine. It is built using the Flask Framework and deployed on Heroku Cloud Platform.
----------------------------------------------------------------------------------------------------
INSERT INTO PROJECTS (TID, PROJECT_NAME, GIT_LINK, DEPLOYMENT_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB805","Red Wine Quality Prediction using Decision Tree Algorithm", "", "https://redwine-quality-prediction.herokuapp.com/", "08/2021", "08/2021", "2", "This Machine Learning Model is able to assign a quality score to the Red Wine based upon the properties/composition of the Wine. It is built using the Flask Framework and deployed on Heroku Cloud Platform.")
tid ->  TB806
project_name ->  Woman Affair Classification using Logistic Regression
project_deployment_link ->  http://woman-affair-classifier.herokuapp.com/
start date ->  07/2021
end date ->  07/2021
details ->  A Webpage that takes in all the required details of a Woman and is able to predict whether the woman has any affair or not. This project is built using the Flask Framework, it uses the Logistic Regression Algorithm. And this is deployed on Heroku Cloud Platform.
----------------------------------------------------------------------------------------------------
INSERT INTO PROJECTS (TID, PROJECT_NAME, GIT_LINK, DEPLOYMENT_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB806","Woman Affair Classification using Logistic Regression", "", "http://woman-affair-classifier.herokuapp.com/", "07/2021", "07/2021", "2", "A Webpage that takes in all the required details of a Woman and is able to predict whether the woman has any affair or not. This project is built using the Flask Framework, it uses the Logistic Regression Algorithm. And this is deployed on Heroku Cloud Platform.")
tid ->  TB807
project_name ->  Boston Housing Price Prediction using Linear Regression
project_deployment_link ->  https://boston-housing-price-linear.herokuapp.com/
start date ->  07/2021
end date ->  07/2021
details ->  The Project uses the classical Linear Regression Model to predict the Boston House Prices. The Housing Details are provided to the algorithm and the algorithm is able to predict the Housing Prices. This Project is created using the Flask Framework and is deployed on Heroku Cloud Platform.
----------------------------------------------------------------------------------------------------
INSERT INTO PROJECTS (TID, PROJECT_NAME, GIT_LINK, DEPLOYMENT_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB807","Boston Housing Price Prediction using Linear Regression", "", "https://boston-housing-price-linear.herokuapp.com/", "07/2021", "07/2021", "2", "The Project uses the classical Linear Regression Model to predict the Boston House Prices. The Housing Details are provided to the algorithm and the algorithm is able to predict the Housing Prices. This Project is created using the Flask Framework and is deployed on Heroku Cloud Platform.")
tid ->  TB808
project_name ->  Webscapper built using Python's Flask Framework using Selenium
project_deployment_link ->
start date ->  06/2021
end date ->  06/2021
details ->  This web scapper scraps data from MonsterIndia website. It scraps all the Job related details. Built using Selenium and integrated with MongoDB.
----------------------------------------------------------------------------------------------------
INSERT INTO PROJECTS (TID, PROJECT_NAME, GIT_LINK, DEPLOYMENT_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB808","Webscapper built using Python's Flask Framework using Selenium", "", "", "06/2021", "06/2021", "2", "This web scapper scraps data from MonsterIndia website. It scraps all the Job related details. Built using Selenium and integrated with MongoDB.")
tid ->  TB809
project_name ->  Webscrapper built using Python's Flask Framework
project_deployment_link ->  https://flask-fl-scrapper.herokuapp.com/
start date ->  06/2021
end date ->  06/2021
details ->  This is a Web Scrapper built using Python and Flask Framework. It scraps Flipkart's website and shows all the user names, reviews, ratings, and descriptions given by that user. This program is deployed in Heroku Platform.
----------------------------------------------------------------------------------------------------
INSERT INTO PROJECTS (TID, PROJECT_NAME, GIT_LINK, DEPLOYMENT_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB809","Webscrapper built using Python's Flask Framework", "", "https://flask-fl-scrapper.herokuapp.com/", "06/2021", "06/2021", "2", "This is a Web Scrapper built using Python and Flask Framework. It scraps Flipkart's website and shows all the user names, reviews, ratings, and descriptions given by that user. This program is deployed in Heroku Platform.")
tid ->  TB8010
project_name ->  Analysis of Trivial and Bio-inspired Algorithms
project_deployment_link ->  https://github.com/JuelBasak/Final-Project-B.Tech
start date ->  02/2019
end date ->  05/2019
details ->  Bangalore
----------------------------------------------------------------------------------------------------
INSERT INTO PROJECTS (TID, PROJECT_NAME, GIT_LINK, DEPLOYMENT_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB8010","Analysis of Trivial and Bio-inspired Algorithms", "", "https://github.com/JuelBasak/Final-Project-B.Tech", "02/2019", "05/2019", "2", "Bangalore")
tid ->  TB8011
project_name ->  Design and development of an application for Election Analysis and Voting
project_deployment_link ->  https://github.com/JuelBasak/Mini-Project-BTech
start date ->  02/2018
end date ->  05/2018
details ->  Bangalore
----------------------------------------------------------------------------------------------------
INSERT INTO PROJECTS (TID, PROJECT_NAME, GIT_LINK, DEPLOYMENT_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB8011","Design and development of an application for Election Analysis and Voting", "", "https://github.com/JuelBasak/Mini-Project-BTech", "02/2018", "05/2018", "2", "Bangalore")
tid ->  TB8012
project_name ->  Monitor Temperature using IOT Devices
project_deployment_link ->
start date ->  09/2017
end date ->  09/2017
details ->  Bangalore
----------------------------------------------------------------------------------------------------
INSERT INTO PROJECTS (TID, PROJECT_NAME, GIT_LINK, DEPLOYMENT_LINK, START_DATE, END_DATE, DURATION, DETAILS) VALUES ("TB8012","Monitor Temperature using IOT Devices", "", "", "09/2017", "09/2017", "2", "Bangalore")